#Bloque de variables

BANDERAS	= -g -lm --std=C11
SALIDA		= [2021 IS][Datos][Ejercicios 1]AdrianArayaMorera

#Regala que se ejecuta por defecto
all:
		gcc $(BANDERAS) [2021 IS][Datos][Ejercicios 1]AdrianArayaMorera.c -o $(SALIDA)
		
#Regla especial para limpiar
.PHONY clean:
		rm *.o (SALIDA)
